### ISSUE TITLE
Shorthand notations for lambdas

### ISSUE THREAD

**Issue by tfga** [ssledz/bash-fun#1]
Ok, here's what I'd like to do:

1. Be able to `map` an existing command / function:
```bash
$ list 1 2 3 | map echo
1
2
3
```

2. Have a shorthand notation for simple lambdas:
```bash
$ list 1 2 3 | map 'echo $ is a number'
1 is a number
2 is a number
3 is a number
```

Would it be possible to add these to `bash-fun`?

**Comment by ssledz** [comment]
Done. 

Please check if everything is working :)

Best regards,
SS.

**Comment by tfga** [comment]
Yes, it is. :smile: 

Thank you very much.

**Comment by tfga** [comment]
BTW, have you seen this?

https://elv.sh/

It's a shell with lambdas (among other things). I found out about it the other day and it's completely blowing my mind.

I thought you might be interested.
