### ISSUE TITLE
Thanks you for making this!

### ISSUE THREAD

**Issue by anaxios** [ssledz/bash-fun#5]
As a noob to functional programming and programming in general this was a really cool introduction to some functional concepts. 

I started this script that checks for duplicate files by hashing them instead of by file name to play around with some of the concepts. https://github.com/anaxios/dedooper

**Comment by ssledz** [comment]
Nice to hear that the library is useful ! Some times ago I have written two articles about functional programming in bash (all are in polish)

https://nofluffjobs.com/blog/funkcyjne-programowanie-w-bashu-czesc-i/
https://nofluffjobs.com/blog/funkcyjne-programowanie-w-bashu-czesc-2/

All the best,
S.
